function [trainedClassifier, validationAccuracy] = trainEMGClassifier(trainingData)
% [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% Returns a trained classifier and its accuracy. This code recreates the
% classification model trained in Classification Learner app. Use the
% generated code to automate training the same model with new data, or to
% learn how to programmatically train models.
%
%  Input:
%      trainingData: A table containing the same predictor and response
%       columns as those imported into the app.
%
%
%  Output:
%      trainedClassifier: A struct containing the trained classifier. The
%       struct contains various fields with information about the trained
%       classifier.
%
%      trainedClassifier.predictFcn: A function to make predictions on new
%       data.
%
%      validationAccuracy: A double representing the validation accuracy as
%       a percentage. In the app, the Models pane displays the validation
%       accuracy for each model.
%
% Use the code to train the model with new data. To retrain your
% classifier, call the function from the command line with your original
% data or new data as the input argument trainingData.
%
% For example, to retrain a classifier trained with the original data set
% T, enter:
%   [trainedClassifier, validationAccuracy] = trainClassifier(T)
%
% To make predictions with the returned 'trainedClassifier' on new data T2,
% use
%   [yfit,scores] = trainedClassifier.predictFcn(T2)
%
% T2 must be a table containing at least the same predictor columns as used
% during training. For details, enter:
%   trainedClassifier.HowToPredict

% Auto-generated by MATLAB on 03-Feb-2025 14:33:49


% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'max1', 'mean1', 'min1', 'var1', 'max2', 'mean2', 'min2', 'var2', 'max3', 'mean3', 'min3', 'var3', 'max4', 'mean4', 'min4', 'var4', 'max5', 'mean5', 'min5', 'var5', 'max6', 'mean6', 'min6', 'var6', 'max7', 'mean7', 'min7', 'var7', 'max8', 'mean8', 'min8', 'var8'};
predictors = inputTable(:, predictorNames);
response = inputTable.Action;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];
classNames = categorical({'Chuck Grip'; 'Fine Pinch'; 'H. Open'; 'Hook Grip'; 'Key Grip'; 'No Move'; 'Power Grip'; 'Thumb Enclosed'; 'Tool Grip'; 'W. Abduction'; 'W. Adduction'; 'W. Extension'; 'W. Flexion'; 'W. Pronation'; 'W. Supination'});

% Train a classifier
% This code specifies all the classifier options and trains the classifier.
template = templateLinear(...
    'Learner', 'SVM', ...
    'Lambda', 'auto', ...
    'BetaTolerance', 0.0001);
classificationLinear = fitcecoc(...
    predictors, ...
    response, ...
    'Learners', template, ...
    'Coding', 'onevsone', ...
    'ClassNames', classNames);

% Create the result struct with predict function
predictorExtractionFcn = @(t) t(:, predictorNames);
classificationLinearPredictFcn = @(x) predict(classificationLinear, x);
trainedClassifier.predictFcn = @(x) classificationLinearPredictFcn(predictorExtractionFcn(x));

% Add additional fields to the result struct
trainedClassifier.RequiredVariables = {'max1', 'mean1', 'min1', 'var1', 'max2', 'mean2', 'min2', 'var2', 'max3', 'mean3', 'min3', 'var3', 'max4', 'mean4', 'min4', 'var4', 'max5', 'mean5', 'min5', 'var5', 'max6', 'mean6', 'min6', 'var6', 'max7', 'mean7', 'min7', 'var7', 'max8', 'mean8', 'min8', 'var8'};
trainedClassifier.ClassificationLinear = classificationLinear;
trainedClassifier.About = 'This struct is a trained model exported from Classification Learner R2024b.';
trainedClassifier.HowToPredict = sprintf('To make predictions on a new table, T, use: \n  [yfit,scores] = c.predictFcn(T) \nreplace ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nThe table, T, must contain the variables returned by: \n  c.RequiredVariables \nVariable formats (e.g. matrix/vector, datatype) must match the original training data. \nAdditional variables are ignored. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appclassification_exportmodeltoworkspace'')">How to predict using an exported model</a>.');

% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'max1', 'mean1', 'min1', 'var1', 'max2', 'mean2', 'min2', 'var2', 'max3', 'mean3', 'min3', 'var3', 'max4', 'mean4', 'min4', 'var4', 'max5', 'mean5', 'min5', 'var5', 'max6', 'mean6', 'min6', 'var6', 'max7', 'mean7', 'min7', 'var7', 'max8', 'mean8', 'min8', 'var8'};
predictors = inputTable(:, predictorNames);
response = inputTable.Action;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];
classNames = categorical({'Chuck Grip'; 'Fine Pinch'; 'H. Open'; 'Hook Grip'; 'Key Grip'; 'No Move'; 'Power Grip'; 'Thumb Enclosed'; 'Tool Grip'; 'W. Abduction'; 'W. Adduction'; 'W. Extension'; 'W. Flexion'; 'W. Pronation'; 'W. Supination'});

% Perform cross-validation
KFolds = 5;
cvp = cvpartition(response, 'KFold', KFolds);
% Initialize the predictions to the proper sizes
validationPredictions = response;
numObservations = size(predictors, 1);
numClasses = 15;
validationScores = NaN(numObservations, numClasses);
for fold = 1:KFolds
    trainingPredictors = predictors(cvp.training(fold), :);
    trainingResponse = response(cvp.training(fold), :);
    foldIsCategoricalPredictor = isCategoricalPredictor;

    % Train a classifier
    % This code specifies all the classifier options and trains the classifier.
    template = templateLinear(...
        'Learner', 'SVM', ...
        'Lambda', 'auto', ...
        'BetaTolerance', 0.0001);
    classificationLinear = fitcecoc(...
        trainingPredictors, ...
        trainingResponse, ...
        'Learners', template, ...
        'Coding', 'onevsone', ...
        'ClassNames', classNames);

    % Create the result struct with predict function
    classificationLinearPredictFcn = @(x) predict(classificationLinear, x);
    validationPredictFcn = @(x) classificationLinearPredictFcn(x);

    % Add additional fields to the result struct

    % Compute validation predictions
    validationPredictors = predictors(cvp.test(fold), :);
    [foldPredictions, foldScores] = validationPredictFcn(validationPredictors);

    % Store predictions in the original order
    validationPredictions(cvp.test(fold), :) = foldPredictions;
    validationScores(cvp.test(fold), :) = foldScores;
end

% Compute validation accuracy
correctPredictions = (validationPredictions == response);
isMissing = ismissing(response);
correctPredictions = correctPredictions(~isMissing);
validationAccuracy = sum(correctPredictions)/length(correctPredictions);